FROM alpine

RUN apk add --no-cache --update \
    bash \
    conntrack-tools \
    coreutils \
    curl \
    drill \
    iperf3 \
    iproute2 \
    iptables \
    iputils \
    ip6tables \
    keepalived \
    net-tools \
    nftables \
    socat \
    ethtool \
    mtr \
    wget \
    nmap \
    tcpdump \
    bind-tools \
    busybox-extras \
    ipvsadm \
    iperf

WORKDIR /osm
COPY scripts/network-diagnostic.sh .